name: academic_flutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.13
  lottie: ^1.0.1
  gif: ^2.2.0 
  sizer: ^2.0.15
  animate_do: ^2.0.1
  http: ^0.13.3
  google_fonts: ^3.0.1
  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.3
  smooth_page_indicator: ^1.0.0
  badges: ^3.1.2
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

assets:  
   - assets/images/main_top.png
   - assets/images/login_bottom.png
